# Generated by Django 4.2.16 on 2024-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
